services:
  express-instance-1:
    image: my-express-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-instance-1
    environment:
      - CONTAINER_NAME=express-instance-1
    networks:
      - my-app-network

  express-instance-2:
    image: my-express-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-instance-2
    environment:
      - CONTAINER_NAME=express-instance-2
    networks:
      - my-app-network

  express-instance-3:
    image: my-express-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-instance-3
    environment:
      - CONTAINER_NAME=express-instance-3
    networks:
      - my-app-network

  nginx-lb:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - express-instance-1
      - express-instance-2
      - express-instance-3
    networks:
      - my-app-network

networks:
  my-app-network:
    driver: bridge